JBAI-726 memory management
JetBrains-Research/kinference pull request #170
Opened 2024-02-08 17:38 UTC by dmitriyb

- ArrayDispatcher allocates and stores arrays of primitive types for all tensors in a centralized manner
- Used in the allocation of all tensors through the PrimitiveTileArray constructor
- It controls up to 80% of all array allocations
- Is not used in dotTransposedWithAlpha in the current version (further investigation required)

2024-02-14 12:36 UTC, cupertank requested changes

2024-02-14 12:36 UTC, cupertank commented on inference/inference-ir/src/commonMain/kotlin/io/kinference/operator/Operator.kt
> +        var totalOperatorsCount = 0
Looks unsafe

2024-03-22 17:37 UTC, dmitriyb commented on inference/inference-ir/src/commonMain/kotlin/io/kinference/operator/Operator.kt
> +        var totalOperatorsCount = 0
This part was completely rewritten

2024-03-22 18:21 UTC, cupertank requested changes

2024-03-27 20:47 UTC, cupertank approved these changes

2024-03-28 08:04 UTC, merged