Some optimizations
JetBrains-Research/kinference pull request #61
Opened 2023-03-08 14:50 UTC by cupertank

2023-03-08 16:34 UTC, AnastasiaTuchina requested changes

2023-03-08 16:34 UTC, AnastasiaTuchina commented on inference/inference-core/src/commonMain/kotlin/io/kinference.core/operators/math/BiasGelu.kt
>          private fun computeDouble(output: DoubleNDArray, input: DoubleNDArray, bias: DoubleNDArray, startOffset: Int = 0, count: Int = input.linearSize - startOffset) {
Add the optimizations for double, please...

2023-03-08 16:34 UTC, AnastasiaTuchina commented on inference/inference-core/src/commonMain/kotlin/io/kinference.core/operators/math/BiasGelu.kt
> +                //1720
1720 what?

2023-03-08 16:34 UTC, AnastasiaTuchina commented on inference/inference-core/src/commonMain/kotlin/io/kinference.core/operators/math/BiasGelu.kt
> +            val batchSize = run {
Actually, all of these block size functions follow the same pattern. Maybe you can put this as a function somewhere in utils instead(and docs, please)?

2023-03-08 16:34 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/arrays/PrimitiveNDArray.kt
> +        val batchSize = let {
Separate function

2023-03-08 16:34 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/PrimitiveExtensions.kt
> +    val batchSize = run {
Separate function

2023-03-08 16:34 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/Softmax.kt
> +    val maxBatchSize = run {
Separate function

2023-03-08 16:34 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/Softmax.kt
> +    val minusBatchSize = run {
Separate this one too

2023-03-08 16:34 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/Softmax.kt
> +    val expBatchSize = run {
And this

2023-03-09 17:37 UTC, AnastasiaTuchina requested changes

2023-03-09 17:37 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/biasGelu/BiasGelu.kt
> +    ) { "BiasGelu operation supported only for DoubleNDArray and FloatNDArray" }
Maybe put the actual data types of input and bias in this error message?

2023-03-09 17:37 UTC, AnastasiaTuchina commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/softmax/Softmax.kt
> +    require(input.type == DataType.FLOAT || input.type == DataType.DOUBLE) { "Softmax operation supported only for DoubleNDArray and FloatNDArray" }
Actual data type as well

2023-03-10 11:09 UTC, TanVD requested changes

2023-03-10 11:09 UTC, TanVD commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/Utils.kt
> +                                function: (blockStart: Int, blockEnd: Int) -> Unit) {
By convention, we call it "body"

2023-03-10 11:09 UTC, TanVD commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/Utils.kt
> +suspend inline fun parallelizeByRows(rowSize: Int, countRows: Int, minDataPerLaunch: Int, noinline function: (rowStart: Int, rowEnd: Int) -> Unit) = parallelizeByBlocks(rowSize, countRows, minDataPer
Why do you need suspend modifier for inline function? You can just inline internal callback as well, and then inline function will work in every code: both suspendable and non-suspendable.

2023-03-10 11:09 UTC, TanVD commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/arrays/PrimitiveNDArray.kt
> +        parallelizeByRows(nRowFlop, n, 261120) { nStart, nEnd ->
A bit of information regarding that magic constant?

2023-03-10 11:09 UTC, TanVD commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/PrimitiveExtensions.kt
> +    parallelizeByRows(rowFlop, n, 262144) { nStart: Int, nEnd: Int ->
And here

2023-03-10 11:09 UTC, TanVD commented on ndarray/ndarray-core/src/commonMain/kotlin/io/kinference/ndarray/extensions/softmax/SoftmaxPrimitive.kt
> +    parallelizeByRows(columns, rows, 1048576) { rowStart, rowEnd ->
And here

2023-03-10 13:32 UTC, TanVD approved these changes

2023-03-10 13:37 UTC, AnastasiaTuchina approved these changes

2023-03-10 13:38 UTC, merged